<?php
include 'connect.php';
if (isset($_POST['submit'])){
$surname=$_POST['surname'];
$othernames=$_POST['othernames'];
$sex=$_POST['sex'];
$mstatus=$_POST['mstatus'];
$cnumber=$_POST['cnumber'];
$bank=$_POST['bank'];
$account=$_POST['account'];
$institution=$_POST['institution'];
$qualification=$_POST['qualification'];
$discipline=$_POST['discipline'];
$mobile=$_POST['mobile'];
$state=$_POST['state'];
$lga=$_POST['lga'];
$hometown=$_POST['hometown'];
$address=$_POST['address'];
$ppa=$_POST['ppa'];
$health=$_POST['health'];
$empname=$_POST['empname'];
$emphone=$_POST['emphone'];
$nextofkin=$_POST['nextofkin'];
$relationship=$_POST['relationship'];
$nextnumber=$_POST['nextnumber'];
$emergency=$_POST['emergency'];
$relationship2=$_POST['relationship2'];
$emgphone=$_POST['emgphone'];
$email=$_POST['email'];

// inser query

$sql="insert into `corpers`(surname,othernames,sex,mstatus,cnumber,bank,account,institution,qualification,discipline,mobile,state,lga,hometown,address,ppa,health,empname,emphone,nextofkin,relationship,nextnumber,emergency,relationship2,emgphone,email) Values ('$surname', '$othernames', '$sex', '$mstatus', '$cnumber', '$bank', '$account', '$institution', '$qualification', '$discipline', '$mobile', '$state', '$lga', '$hometown', '$address', '$ppa', '$health', '$empname', '$emphone', '$nextofkin', '$relationship', '$nextnumber', '$emergency', '$relationship2', '$emgphone', '$email')";

$result=mysqli_query($con,$sql);
if($result){
  echo 'Data submitted successfully';
}else {
  die(mysqli_error($con));
}

}
?>


<!DOCTYPE html><html lang="en" class="h-full w-full">
<!-- Mirrored from www.ndaapplications.net/register by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 03 Mar 2023 12:13:24 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head><meta charSet="utf-8"/>
<title>Giade Corpers e-Registration Portal</title>
<meta content="width=device-width,initial-scale=1" name="viewport"/>
<link rel="stylesheet" href="build/_assets/app-FB3LH2MQ.css"/>
<link rel="stylesheet" href="build/_assets/ReactToastify-VA75UTYY.css"/>
<link rel="stylesheet" href="build/_assets/nprogress-JFUSETFZ.css"/></head>
<body class="h-full w-full"><div class="min-h-full flex flex-row-reverse">
<div class="flex-1 flex flex-col justify-center py-12 px-4 sm:px-6 lg:flex-none lg:px-20 xl:px-24"><div class="mx-auto w-full  lg:w-[32rem]"><div><a class="flex justify-center" href="index.html"><img src="nda-logo2.png" alt="" class="h-24 w-auto object-center"/></a>
<h2 class="mt-3 text-3xl font-headings text-center font-extrabold text-gray-900">Register an account</h2>
<p class="mt-1 text-sm text-center text-gray-600"><a class="font-medium text-center text-primary-600 hover:text-primary-500" href="login.html">Already have an account? Login here!</a></p></div>
<div class="mt-5"><div class="mt-6"><form method="post" action="#" encType="application/x-www-form-urlencoded" class="space-y-3">
  <div><div class="flex justify-between"><label for="surname" class="block text-sm font-medium text-gray-700">Surname<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Surname" id="surname" name="surname" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div><div><div class="flex justify-between"><label for="othernames" class="block text-sm font-medium text-gray-700">Other Names<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div>
<div class="mt-1 relative"><input type="text" placeholder="Other Names" id="othernames" name="othernames" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div>
<div class="md:flex space-y-3 md:space-y-0 md:space-x-2"><div class="w-full"><div class="flex justify-between"><label for="sex" class="block text-sm font-medium text-gray-700">Sex<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Are you a male or female ?" id="email" name="sex" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div><div class="w-full"><div class="flex justify-between"><label for="email" class="block text-sm font-medium text-gray-700">Marital Status<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Are you married or single ?" id="email" name="mstatus" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div></div><div><div class="flex justify-between"><label for="surname" class="block text-sm font-medium text-gray-700">Call-up Number<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Call-up Number" id="surname" name="cnumber" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div>
<div class="md:flex space-y-3 md:space-y-0 md:space-x-2"><div class="w-full"><div class="flex justify-between"><label for="bankname" class="block text-sm font-medium text-gray-700">Bank Name<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div>
<div class="mt-1 relative"><input type="text" placeholder="Bank Name" id="text" name="bank" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div><div class="w-full"><div class="flex justify-between"><label for="accountnumber" class="block text-sm font-medium text-gray-700">Account Number<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="tel" placeholder="Account Number" id="email" name="account" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div></div>
<div><div class="flex justify-between"><label for="institution" class="block text-sm font-medium text-gray-700">Institution of Graduation<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Institution of Graduation" id="othernames" name="institution" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div>
<div class="md:flex space-y-3 md:space-y-0 md:space-x-2"><div class="w-full"><div class="flex justify-between"><label for="qualification" class="block text-sm font-medium text-gray-700">Qualification<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Qualification" id="email" name="qualification" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div><div class="w-full"><div class="flex justify-between"><label for="discipline" class="block text-sm font-medium text-gray-700">Discipline<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Discipline"id="email" name="discipline" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div></div>
<div><div class="flex justify-between"><label for="mobile" class="block text-sm font-medium text-gray-700">Mobile Number<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="tel" placeholder="Mobile Number" id="othernames" name="mobile" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div>
<div class="md:flex space-y-3 md:space-y-0 md:space-x-2"><div class="w-full"><div class="flex justify-between"><label for="state" class="block text-sm font-medium text-gray-700">State of Origin<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="State of Origin" id="password" name="state" autoComplete="off" required="" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div><div class="w-full"><div class="flex justify-between"><label for="lga" class="block text-sm font-medium text-gray-700">L.G.A<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Local Government Area" id="confirm-password" name="lga" autoComplete="off" required="" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div></div>
<div><div class="flex justify-between"><label for="mobile" class="block text-sm font-medium text-gray-700">Home Town<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Home Town" id="othernames" name="hometown" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div>
<div class="md:flex space-y-3 md:space-y-0 md:space-x-2"><div class="w-full"><div class="flex justify-between"><label for="address" class="block text-sm font-medium text-gray-700">Contact Address<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Contact Address" id="password" name="address" autoComplete="off" required="" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div><div class="w-full"><div class="flex justify-between"><label for="ppa" class="block text-sm font-medium text-gray-700">Place of Primary Assignment<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="PPA" id="confirm-password" name="ppa" autoComplete="off" required="" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div></div>
<div><div class="flex justify-between"><label for="health" class="block text-sm font-medium text-gray-700">Health Status<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Do you have any health condition?" id="othernames" name="health" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div>
<div class="md:flex space-y-3 md:space-y-0 md:space-x-2"><div class="w-full"><div class="flex justify-between"><label for="employer" class="block text-sm font-medium text-gray-700">Employer's Name<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Employer's full name" id="password" name="empname" autoComplete="off" required="" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div><div class="w-full"><div class="flex justify-between"><label for="emphone" class="block text-sm font-medium text-gray-700">Employer's Phone Number<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Employer's Phone Number" id="confirm-password" name="emphone" autoComplete="off" required="" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div></div>
<div><div class="flex justify-between"><label for="nextofkin" class="block text-sm font-medium text-gray-700">Next of kin<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Full name of next of kin" id="othernames" name="nextofkin" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div>
<div class="md:flex space-y-3 md:space-y-0 md:space-x-2"><div class="w-full"><div class="flex justify-between"><label for="relationship" class="block text-sm font-medium text-gray-700">Relationship<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Relationship" id="password" name="relationship" autoComplete="off" required="" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div><div class="w-full"><div class="flex justify-between"><label for="nextnumber" class="block text-sm font-medium text-gray-700">Next of kin's Phone Number<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="tel" placeholder="Phone Number" id="confirm-password" name="nextnumber" autoComplete="off" required="" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div></div>
<div><div class="flex justify-between"><label for="nextofkin" class="block text-sm font-medium text-gray-700">Emergency<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Who do we contact inthe case of emergency?" id="othernames" name="emergency" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div>
<div class="md:flex space-y-3 md:space-y-0 md:space-x-2"><div class="w-full"><div class="flex justify-between"><label for="relationship2" class="block text-sm font-medium text-gray-700">Relationship<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="text" placeholder="Relationship" id="password" name="relationship2" autoComplete="off" required="" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div><div class="w-full"><div class="flex justify-between"><label for="emgphone" class="block text-sm font-medium text-gray-700">Phone Number<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="tel" placeholder="Emergency's Phone Number" id="confirm-password" name="emgphone" autoComplete="off" required="" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div></div>
<div><div class="flex justify-between"><label for="nextofkin" class="block text-sm font-medium text-gray-700">Email<span class="bg-gray-200 rounded px-1 text-[0.6rem] text-gray-600 inline-block uppercase tracking-wide ml-3">required</span></label></div><div class="mt-1 relative"><input type="email" placeholder="Enter email address" id="othernames" name="email" autoComplete="off" required="" aria-invalid="false" class="appearance-none disabled:text-gray-700 disabled:bg-gray-200 disabled:cursor-not-allowed block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"/></div></div>
<div><button type="submit"  name='submit' class="w-full flex justify-center items-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"> Submit</button></div><div class="py-2"></div></form></div></div></div></div><div class="hidden lg:block relative w-0 flex-1 bg-primary-50"><div class="h-full flex flex-col justify-center items-center"><img src="nda-logo2.png" alt="" class="h-36 w-auto object-center"/><p class="text-2xl tracking-wide font-semibold font-headings">Welcome To The Giade (C.D.S) Portal</p><span class="text-slate-600 text-sm font-medium">Giade Corpers e-Registration page</span></div></div></div></body></html>

<!------------------------------------------------------------

